# Generated by Django 5.2 on 2025-08-21 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='descrition',
            new_name='description',
        ),
    ]
