# Generated by Django 5.2 on 2025-09-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='descrition',
            new_name='description',
        ),
    ]
